env:
  global:
    - CC_TEST_REPORTER_ID=aa7d09060adc8243f2a6f51b6051ea2629b2f9a3c28042076f2494193bc8ad06
language: java
git:
  submodules: false
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - mvn -f pom-public.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - mvn -f pom-public.xml test jacoco:report -B
after_script:
  - rm -fv ./target/site/jacoco/jacoco.xml
  - cp -fv ./target/site/jacoco/jacoco.xml ./
  - cp -frv ./src/main/kotlin/* ./
  - cp -frv ./src/main/java/* ./
  - ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT --coverage-input-type jacoco --prefix /home/travis/build/Bloombox/Java/src/main/java
