env:
  global:
    - CC_TEST_REPORTER_ID=aa7d09060adc8243f2a6f51b6051ea2629b2f9a3c28042076f2494193bc8ad06
language: java
git:
  submodules: false
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - mvn test -B
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

