env:
  global:
    - CC_TEST_REPORTER_ID=aa7d09060adc8243f2a6f51b6051ea2629b2f9a3c28042076f2494193bc8ad06
    - CODACY_PROJECT_TOKEN=b61ce006b9444d58929dff058f06be2d
  matrix:
    - BUILDMODE=maven
    - BUILDMODE=gradle
language: java
cache:
  directories:
  - $HOME/.m2
branches:
  except:
    - embedded
git:
  submodules: false
jdk:
  - oraclejdk8
  - openjdk8
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.m2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - curl -L https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar > ./codacy-coverage-reporter.jar
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - make build-ci BUILDMODE=$BUILDMODE
script:
  - make run-ci BUILDMODE=$BUILDMODE
after_script:
  - rm -fv ./jacoco.xml
  - cp -fv ./target/site/jacoco/jacoco.xml ./
  - cp -frv ./src/main/kotlin/* ./
  - cp -frv ./src/main/java/* ./
  - ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT --coverage-input-type jacoco --prefix /home/travis/build/Bloombox/Java/src/main/java
  - java -cp codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml

