/*
 * Copyright 2018, Bloombox, LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner/settings/PartnerLocationSettings.proto

package io.bloombox.schema.partner.settings;

/**
 * <pre>
 * Specifies settings related to shop comms.
 * </pre>
 *
 * Protobuf type {@code bloombox.schema.partner.settings.ShopCommsSettings}
 */
public  final class ShopCommsSettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bloombox.schema.partner.settings.ShopCommsSettings)
    ShopCommsSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShopCommsSettings.newBuilder() to construct.
  private ShopCommsSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShopCommsSettings() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShopCommsSettings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder subBuilder = null;
            if (internal_ != null) {
              subBuilder = internal_.toBuilder();
            }
            internal_ = input.readMessage(io.bloombox.schema.partner.settings.CommsSettingsPayload.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(internal_);
              internal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder subBuilder = null;
            if (external_ != null) {
              subBuilder = external_.toBuilder();
            }
            external_ = input.readMessage(io.bloombox.schema.partner.settings.CommsSettingsPayload.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(external_);
              external_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bloombox.schema.partner.settings.PartnerLocationSettingsOuterClass.internal_static_bloombox_schema_partner_settings_ShopCommsSettings_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bloombox.schema.partner.settings.PartnerLocationSettingsOuterClass.internal_static_bloombox_schema_partner_settings_ShopCommsSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bloombox.schema.partner.settings.ShopCommsSettings.class, io.bloombox.schema.partner.settings.ShopCommsSettings.Builder.class);
  }

  public static final int INTERNAL_FIELD_NUMBER = 1;
  private io.bloombox.schema.partner.settings.CommsSettingsPayload internal_;
  /**
   * <pre>
   * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
   */
  public boolean hasInternal() {
    return internal_ != null;
  }
  /**
   * <pre>
   * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
   */
  public io.bloombox.schema.partner.settings.CommsSettingsPayload getInternal() {
    return internal_ == null ? io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : internal_;
  }
  /**
   * <pre>
   * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
   */
  public io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder getInternalOrBuilder() {
    return getInternal();
  }

  public static final int EXTERNAL_FIELD_NUMBER = 2;
  private io.bloombox.schema.partner.settings.CommsSettingsPayload external_;
  /**
   * <pre>
   * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
   * customers, and so on.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
   */
  public boolean hasExternal() {
    return external_ != null;
  }
  /**
   * <pre>
   * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
   * customers, and so on.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
   */
  public io.bloombox.schema.partner.settings.CommsSettingsPayload getExternal() {
    return external_ == null ? io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : external_;
  }
  /**
   * <pre>
   * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
   * customers, and so on.
   * </pre>
   *
   * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
   */
  public io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder getExternalOrBuilder() {
    return getExternal();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (internal_ != null) {
      output.writeMessage(1, getInternal());
    }
    if (external_ != null) {
      output.writeMessage(2, getExternal());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (internal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInternal());
    }
    if (external_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExternal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bloombox.schema.partner.settings.ShopCommsSettings)) {
      return super.equals(obj);
    }
    io.bloombox.schema.partner.settings.ShopCommsSettings other = (io.bloombox.schema.partner.settings.ShopCommsSettings) obj;

    boolean result = true;
    result = result && (hasInternal() == other.hasInternal());
    if (hasInternal()) {
      result = result && getInternal()
          .equals(other.getInternal());
    }
    result = result && (hasExternal() == other.hasExternal());
    if (hasExternal()) {
      result = result && getExternal()
          .equals(other.getExternal());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInternal()) {
      hash = (37 * hash) + INTERNAL_FIELD_NUMBER;
      hash = (53 * hash) + getInternal().hashCode();
    }
    if (hasExternal()) {
      hash = (37 * hash) + EXTERNAL_FIELD_NUMBER;
      hash = (53 * hash) + getExternal().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.partner.settings.ShopCommsSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bloombox.schema.partner.settings.ShopCommsSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Specifies settings related to shop comms.
   * </pre>
   *
   * Protobuf type {@code bloombox.schema.partner.settings.ShopCommsSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bloombox.schema.partner.settings.ShopCommsSettings)
      io.bloombox.schema.partner.settings.ShopCommsSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bloombox.schema.partner.settings.PartnerLocationSettingsOuterClass.internal_static_bloombox_schema_partner_settings_ShopCommsSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bloombox.schema.partner.settings.PartnerLocationSettingsOuterClass.internal_static_bloombox_schema_partner_settings_ShopCommsSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bloombox.schema.partner.settings.ShopCommsSettings.class, io.bloombox.schema.partner.settings.ShopCommsSettings.Builder.class);
    }

    // Construct using io.bloombox.schema.partner.settings.ShopCommsSettings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (internalBuilder_ == null) {
        internal_ = null;
      } else {
        internal_ = null;
        internalBuilder_ = null;
      }
      if (externalBuilder_ == null) {
        external_ = null;
      } else {
        external_ = null;
        externalBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bloombox.schema.partner.settings.PartnerLocationSettingsOuterClass.internal_static_bloombox_schema_partner_settings_ShopCommsSettings_descriptor;
    }

    public io.bloombox.schema.partner.settings.ShopCommsSettings getDefaultInstanceForType() {
      return io.bloombox.schema.partner.settings.ShopCommsSettings.getDefaultInstance();
    }

    public io.bloombox.schema.partner.settings.ShopCommsSettings build() {
      io.bloombox.schema.partner.settings.ShopCommsSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.bloombox.schema.partner.settings.ShopCommsSettings buildPartial() {
      io.bloombox.schema.partner.settings.ShopCommsSettings result = new io.bloombox.schema.partner.settings.ShopCommsSettings(this);
      if (internalBuilder_ == null) {
        result.internal_ = internal_;
      } else {
        result.internal_ = internalBuilder_.build();
      }
      if (externalBuilder_ == null) {
        result.external_ = external_;
      } else {
        result.external_ = externalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bloombox.schema.partner.settings.ShopCommsSettings) {
        return mergeFrom((io.bloombox.schema.partner.settings.ShopCommsSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bloombox.schema.partner.settings.ShopCommsSettings other) {
      if (other == io.bloombox.schema.partner.settings.ShopCommsSettings.getDefaultInstance()) return this;
      if (other.hasInternal()) {
        mergeInternal(other.getInternal());
      }
      if (other.hasExternal()) {
        mergeExternal(other.getExternal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bloombox.schema.partner.settings.ShopCommsSettings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bloombox.schema.partner.settings.ShopCommsSettings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.bloombox.schema.partner.settings.CommsSettingsPayload internal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder> internalBuilder_;
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public boolean hasInternal() {
      return internalBuilder_ != null || internal_ != null;
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayload getInternal() {
      if (internalBuilder_ == null) {
        return internal_ == null ? io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : internal_;
      } else {
        return internalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public Builder setInternal(io.bloombox.schema.partner.settings.CommsSettingsPayload value) {
      if (internalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        internal_ = value;
        onChanged();
      } else {
        internalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public Builder setInternal(
        io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder builderForValue) {
      if (internalBuilder_ == null) {
        internal_ = builderForValue.build();
        onChanged();
      } else {
        internalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public Builder mergeInternal(io.bloombox.schema.partner.settings.CommsSettingsPayload value) {
      if (internalBuilder_ == null) {
        if (internal_ != null) {
          internal_ =
            io.bloombox.schema.partner.settings.CommsSettingsPayload.newBuilder(internal_).mergeFrom(value).buildPartial();
        } else {
          internal_ = value;
        }
        onChanged();
      } else {
        internalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public Builder clearInternal() {
      if (internalBuilder_ == null) {
        internal_ = null;
        onChanged();
      } else {
        internal_ = null;
        internalBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder getInternalBuilder() {
      
      onChanged();
      return getInternalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder getInternalOrBuilder() {
      if (internalBuilder_ != null) {
        return internalBuilder_.getMessageOrBuilder();
      } else {
        return internal_ == null ?
            io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : internal_;
      }
    }
    /**
     * <pre>
     * Internal communications settings. This includes dispensary owners/operators/staff and other internal stakeholders.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload internal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder> 
        getInternalFieldBuilder() {
      if (internalBuilder_ == null) {
        internalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder>(
                getInternal(),
                getParentForChildren(),
                isClean());
        internal_ = null;
      }
      return internalBuilder_;
    }

    private io.bloombox.schema.partner.settings.CommsSettingsPayload external_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder> externalBuilder_;
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public boolean hasExternal() {
      return externalBuilder_ != null || external_ != null;
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayload getExternal() {
      if (externalBuilder_ == null) {
        return external_ == null ? io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : external_;
      } else {
        return externalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public Builder setExternal(io.bloombox.schema.partner.settings.CommsSettingsPayload value) {
      if (externalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        external_ = value;
        onChanged();
      } else {
        externalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public Builder setExternal(
        io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder builderForValue) {
      if (externalBuilder_ == null) {
        external_ = builderForValue.build();
        onChanged();
      } else {
        externalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public Builder mergeExternal(io.bloombox.schema.partner.settings.CommsSettingsPayload value) {
      if (externalBuilder_ == null) {
        if (external_ != null) {
          external_ =
            io.bloombox.schema.partner.settings.CommsSettingsPayload.newBuilder(external_).mergeFrom(value).buildPartial();
        } else {
          external_ = value;
        }
        onChanged();
      } else {
        externalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public Builder clearExternal() {
      if (externalBuilder_ == null) {
        external_ = null;
        onChanged();
      } else {
        external_ = null;
        externalBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder getExternalBuilder() {
      
      onChanged();
      return getExternalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    public io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder getExternalOrBuilder() {
      if (externalBuilder_ != null) {
        return externalBuilder_.getMessageOrBuilder();
      } else {
        return external_ == null ?
            io.bloombox.schema.partner.settings.CommsSettingsPayload.getDefaultInstance() : external_;
      }
    }
    /**
     * <pre>
     * External communications settings. This specifies settings that apply when communicating with end-users, consumers,
     * customers, and so on.
     * </pre>
     *
     * <code>.bloombox.schema.partner.settings.CommsSettingsPayload external = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder> 
        getExternalFieldBuilder() {
      if (externalBuilder_ == null) {
        externalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.bloombox.schema.partner.settings.CommsSettingsPayload, io.bloombox.schema.partner.settings.CommsSettingsPayload.Builder, io.bloombox.schema.partner.settings.CommsSettingsPayloadOrBuilder>(
                getExternal(),
                getParentForChildren(),
                isClean());
        external_ = null;
      }
      return externalBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bloombox.schema.partner.settings.ShopCommsSettings)
  }

  // @@protoc_insertion_point(class_scope:bloombox.schema.partner.settings.ShopCommsSettings)
  private static final io.bloombox.schema.partner.settings.ShopCommsSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bloombox.schema.partner.settings.ShopCommsSettings();
  }

  public static io.bloombox.schema.partner.settings.ShopCommsSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShopCommsSettings>
      PARSER = new com.google.protobuf.AbstractParser<ShopCommsSettings>() {
    public ShopCommsSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShopCommsSettings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShopCommsSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShopCommsSettings> getParserForType() {
    return PARSER;
  }

  public io.bloombox.schema.partner.settings.ShopCommsSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

