// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content/Content.proto

package io.bloombox.schema.content;

public interface ContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:content.Content)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.content.Content.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.content.Content.Type type = 1;</code>
   */
  io.bloombox.schema.content.Content.Type getType();

  /**
   * <code>.content.Content.Encoding encoding = 2;</code>
   */
  int getEncodingValue();
  /**
   * <code>.content.Content.Encoding encoding = 2;</code>
   */
  io.bloombox.schema.content.Content.Encoding getEncoding();

  /**
   * <code>bytes content = 3;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>.base.Language language = 4;</code>
   */
  int getLanguageValue();
  /**
   * <code>.base.Language language = 4;</code>
   */
  io.bloombox.schema.base.Language getLanguage();

  /**
   * <code>.base.Compression compression = 5;</code>
   */
  boolean hasCompression();
  /**
   * <code>.base.Compression compression = 5;</code>
   */
  io.bloombox.schema.base.Compression getCompression();
  /**
   * <code>.base.Compression compression = 5;</code>
   */
  io.bloombox.schema.base.CompressionOrBuilder getCompressionOrBuilder();
}
