// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content/Name.proto

package io.bloombox.schema.content;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:content.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * basic name
   * </pre>
   *
   * <code>string primary = 1;</code>
   */
  java.lang.String getPrimary();
  /**
   * <pre>
   * basic name
   * </pre>
   *
   * <code>string primary = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrimaryBytes();

  /**
   * <pre>
   * display name 
   * </pre>
   *
   * <code>string display = 2;</code>
   */
  java.lang.String getDisplay();
  /**
   * <pre>
   * display name 
   * </pre>
   *
   * <code>string display = 2;</code>
   */
  com.google.protobuf.ByteString
      getDisplayBytes();
}
