/*
 * Copyright 2018, Bloombox, LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search/SearchSpec.proto

package io.bloombox.schema.search;

public interface ProductResultMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bloombox.schema.search.ProductResultMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Price bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound price = 1;</code>
   */
  boolean hasPrice();
  /**
   * <pre>
   * Price bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound price = 1;</code>
   */
  io.bloombox.schema.search.ProductResultBound getPrice();
  /**
   * <pre>
   * Price bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound price = 1;</code>
   */
  io.bloombox.schema.search.ProductResultBoundOrBuilder getPriceOrBuilder();

  /**
   * <pre>
   * THC bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound thc = 2;</code>
   */
  boolean hasThc();
  /**
   * <pre>
   * THC bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound thc = 2;</code>
   */
  io.bloombox.schema.search.ProductResultBound getThc();
  /**
   * <pre>
   * THC bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound thc = 2;</code>
   */
  io.bloombox.schema.search.ProductResultBoundOrBuilder getThcOrBuilder();

  /**
   * <pre>
   * CBD bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound cbd = 3;</code>
   */
  boolean hasCbd();
  /**
   * <pre>
   * CBD bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound cbd = 3;</code>
   */
  io.bloombox.schema.search.ProductResultBound getCbd();
  /**
   * <pre>
   * CBD bounds.
   * </pre>
   *
   * <code>.bloombox.schema.search.ProductResultBound cbd = 3;</code>
   */
  io.bloombox.schema.search.ProductResultBoundOrBuilder getCbdOrBuilder();
}
