/*
 * Copyright 2018, Bloombox, LLC. All rights reserved.
 *
 * Source and object computer code contained herein is the private intellectual
 * property of Bloombox, a California Limited Liability Corporation. Use of this
 * code in source form requires permission in writing before use or the
 * assembly, distribution, or publishing of derivative works, for commercial
 * purposes or any other purpose, from a duly authorized officer of Momentum
 * Ideas Co.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu/v1beta1/MenuService_Beta1.proto

package io.bloombox.schema.services.menu.v1beta1;

public final class MenuServiceBeta1 {
  private MenuServiceBeta1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_ProductKeyset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_ProductKeyset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Operation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$menu/v1beta1/MenuService_Beta1.proto\022%" +
      "bloombox.schema.services.menu.v1beta1\032\025b" +
      "ase/ProductKey.proto\032\027search/SearchSpec." +
      "proto\032\030products/menu/Menu.proto\032\033product" +
      "s/menu/Section.proto\032\034services/ServiceSt" +
      "atus.proto\032\034google/api/annotations.proto" +
      "\"\362\001\n\004Ping\032\t\n\007Request\032C\n\010Response\0227\n\006stat" +
      "us\030\001 \001(\0162\'.bloombox.schema.services.Serv" +
      "iceStatus\032\231\001\n\tOperation\022D\n\007request\030\001 \001(\013" +
      "23.bloombox.schema.services.menu.v1beta1" +
      ".Ping.Request\022F\n\010response\030\002 \001(\01324.bloomb" +
      "ox.schema.services.menu.v1beta1.Ping.Res" +
      "ponse\"\252\003\n\007GetMenu\032\255\001\n\007Request\022\r\n\005scope\030\001" +
      " \001(\t\022\014\n\004full\030\002 \001(\010\022\021\n\tkeys_only\030\003 \001(\010\022\020\n" +
      "\010snapshot\030\004 \001(\t\022\023\n\013fingerprint\030\005 \001(\t\022<\n\007" +
      "section\030\006 \001(\0162+.opencannabis.products.me" +
      "nu.section.Section\022\r\n\005fresh\030\007 \001(\010\032M\n\010Res" +
      "ponse\0221\n\007catalog\030\001 \001(\0132 .opencannabis.pr" +
      "oducts.menu.Menu\022\016\n\006cached\030\002 \001(\010\032\237\001\n\tOpe" +
      "ration\022G\n\007request\030\001 \001(\01326.bloombox.schem" +
      "a.services.menu.v1beta1.GetMenu.Request\022" +
      "I\n\010response\030\002 \001(\01327.bloombox.schema.serv" +
      "ices.menu.v1beta1.GetMenu.Response\"\351\002\n\013G" +
      "etFeatured\032i\n\007Request\022\r\n\005scope\030\001 \001(\t\022\021\n\t" +
      "keys_only\030\002 \001(\010\022<\n\007section\030\003 \001(\0162+.openc" +
      "annabis.products.menu.section.Section\032E\n" +
      "\010Response\0229\n\010featured\030\001 \003(\0132\'.opencannab" +
      "is.products.menu.MenuProduct\032\247\001\n\tOperati" +
      "on\022K\n\007request\030\001 \001(\0132:.bloombox.schema.se" +
      "rvices.menu.v1beta1.GetFeatured.Request\022" +
      "M\n\010response\030\002 \001(\0132;.bloombox.schema.serv" +
      "ices.menu.v1beta1.GetFeatured.Response\";" +
      "\n\rProductKeyset\022*\n\003key\030\001 \003(\0132\035.opencanna" +
      "bis.base.ProductKey\"\241\002\n\nGetProduct\032%\n\007Re" +
      "quest\022\r\n\005scope\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\032D\n\010Res" +
      "ponse\0228\n\007product\030\002 \003(\0132\'.opencannabis.pr" +
      "oducts.menu.MenuProduct\032\245\001\n\tOperation\022J\n" +
      "\007request\030\001 \001(\01329.bloombox.schema.service" +
      "s.menu.v1beta1.GetProduct.Request\022L\n\010res" +
      "ponse\030\002 \001(\0132:.bloombox.schema.services.m" +
      "enu.v1beta1.GetProduct.Response\"\272\002\n\nSear" +
      "chMenu\032=\n\007Request\0222\n\006search\030\001 \001(\0132\".bloo" +
      "mbox.schema.search.SearchSpec\032E\n\010Respons" +
      "e\0229\n\010resulset\030\001 \001(\0132\'.bloombox.schema.se" +
      "arch.SearchResultset\032\245\001\n\tOperation\022J\n\007re" +
      "quest\030\001 \001(\01329.bloombox.schema.services.m" +
      "enu.v1beta1.SearchMenu.Request\022L\n\010respon" +
      "se\030\002 \001(\0132:.bloombox.schema.services.menu" +
      ".v1beta1.SearchMenu.Response*\260\001\n\tMenuErr" +
      "or\022\014\n\010NO_ERROR\020\000\022\023\n\017PARTNER_INVALID\020\001\022\024\n" +
      "\020LOCATION_INVALID\020\002\022\023\n\017SECTION_INVALID\020\003" +
      "\022\025\n\021SECTION_NOT_FOUND\020\004\022\022\n\016MENU_NOT_FOUN" +
      "D\020\005\022\022\n\016INTERNAL_ERROR\020\006\022\026\n\022SEARCH_UNAVAI" +
      "LABLE\020\0072\271\t\n\004Menu\022\215\001\n\004Ping\0223.bloombox.sch" +
      "ema.services.menu.v1beta1.Ping.Request\0324" +
      ".bloombox.schema.services.menu.v1beta1.P" +
      "ing.Response\"\032\202\323\344\223\002\024\022\022/menu/v1beta1/ping" +
      "\022\206\002\n\010Retrieve\0226.bloombox.schema.services" +
      ".menu.v1beta1.GetMenu.Request\0327.bloombox" +
      ".schema.services.menu.v1beta1.GetMenu.Re" +
      "sponse\"\210\001\202\323\344\223\002\201\001\022</menu/v1beta1/{scope=p" +
      "artners/*/locations/*}/global:retrieveZA" +
      "\022?/menu/v1beta1/{scope=partners/*/locati" +
      "ons/*}/{section}:retrieve\022\240\002\n\010Featured\022:" +
      ".bloombox.schema.services.menu.v1beta1.G" +
      "etFeatured.Request\032;.bloombox.schema.ser" +
      "vices.menu.v1beta1.GetFeatured.Response\"" +
      "\232\001\202\323\344\223\002\223\001\022E/menu/v1beta1/{scope=partners" +
      "/*/locations/*}/global/featured:retrieve" +
      "ZJ\022H/menu/v1beta1/{scope=partners/*/loca" +
      "tions/*}/{section}/featured:retrieve\022\315\001\n" +
      "\010Products\0229.bloombox.schema.services.men" +
      "u.v1beta1.GetProduct.Request\032:.bloombox." +
      "schema.services.menu.v1beta1.GetProduct." +
      "Response\"J\202\323\344\223\002D\022B/menu/v1beta1/{scope=p" +
      "artners/*/locations/*}/products/{key}/de" +
      "tail\022\244\002\n\006Search\0229.bloombox.schema.servic" +
      "es.menu.v1beta1.SearchMenu.Request\032:.blo" +
      "ombox.schema.services.menu.v1beta1.Searc" +
      "hMenu.Response\"\242\001\202\323\344\223\002\233\001\022P/menu/v1beta1/" +
      "{search.options.scope=partners/*/locatio" +
      "ns/*}/search/{search.term}ZG\"B/menu/v1be" +
      "ta1/{search.options.scope=partners/*/loc" +
      "ations/*}/search:\001*B4\n(io.bloombox.schem" +
      "a.services.menu.v1beta1H\001P\001\242\002\003BBSb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opencannabis.schema.base.BaseProductKey.getDescriptor(),
          io.bloombox.schema.search.SearchSpecOuterClass.getDescriptor(),
          io.opencannabis.schema.menu.MenuOuterClass.getDescriptor(),
          io.opencannabis.schema.menu.section.SectionOuterClass.getDescriptor(),
          io.bloombox.schema.services.ServiceStatusOuterClass.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Request_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor.getNestedTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_Ping_Request_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Response_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor.getNestedTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_Ping_Response_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Operation_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_Ping_descriptor.getNestedTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_Ping_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_Ping_Operation_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Request_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor.getNestedTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Request_descriptor,
        new java.lang.String[] { "Scope", "Full", "KeysOnly", "Snapshot", "Fingerprint", "Section", "Fresh", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Response_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor.getNestedTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Response_descriptor,
        new java.lang.String[] { "Catalog", "Cached", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Operation_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_descriptor.getNestedTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetMenu_Operation_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Request_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor.getNestedTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Request_descriptor,
        new java.lang.String[] { "Scope", "KeysOnly", "Section", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Response_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor.getNestedTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Response_descriptor,
        new java.lang.String[] { "Featured", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Operation_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_descriptor.getNestedTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetFeatured_Operation_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_bloombox_schema_services_menu_v1beta1_ProductKeyset_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bloombox_schema_services_menu_v1beta1_ProductKeyset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_ProductKeyset_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Request_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor.getNestedTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Request_descriptor,
        new java.lang.String[] { "Scope", "Key", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Response_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor.getNestedTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Response_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Operation_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_descriptor.getNestedTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_GetProduct_Operation_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor,
        new java.lang.String[] { });
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Request_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor.getNestedTypes().get(0);
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Request_descriptor,
        new java.lang.String[] { "Search", });
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Response_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor.getNestedTypes().get(1);
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Response_descriptor,
        new java.lang.String[] { "Resulset", });
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Operation_descriptor =
      internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_descriptor.getNestedTypes().get(2);
    internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bloombox_schema_services_menu_v1beta1_SearchMenu_Operation_descriptor,
        new java.lang.String[] { "Request", "Response", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.opencannabis.schema.base.BaseProductKey.getDescriptor();
    io.bloombox.schema.search.SearchSpecOuterClass.getDescriptor();
    io.opencannabis.schema.menu.MenuOuterClass.getDescriptor();
    io.opencannabis.schema.menu.section.SectionOuterClass.getDescriptor();
    io.bloombox.schema.services.ServiceStatusOuterClass.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
