/*
 * Copyright 2017, Bloombox, LLC. All rights reserved.
 *
 * Source and object computer code contained herein is the private intellectual
 * property of Bloombox, a California Limited Liability Corporation. Use of this
 * code in source form requires permission in writing before use or the
 * assembly, distribution, or publishing of derivative works, for commercial
 * purposes or any other purpose, from a duly authorized officer of Momentum
 * Ideas Co.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner/PartnerLocation.proto

package io.bloombox.schema.partner;

public final class PartnerLocationOuterClass {
  private PartnerLocationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_partner_PartnerLocationKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_partner_PartnerLocationKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_partner_PartnerLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_partner_PartnerLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035partner/PartnerLocation.proto\022\007partner" +
      "\032\016bq_field.proto\032\025partner/Partner.proto\032" +
      "\025media/MediaItem.proto\032\026temporal/Instant" +
      ".proto\032\031contact/ContactInfo.proto\"\323\001\n\022Pa" +
      "rtnerLocationKey\022W\n\007partner\030\001 \001(\0132\023.part" +
      "ner.PartnerKeyB1\212@.Specifies the partner" +
      " that owns this location.\022d\n\004code\030\002 \001(\tB" +
      "V\212@SShort string that uniquely identifie" +
      "s this location, under a given partner a" +
      "ccount.\"\326\006\n\017PartnerLocation\022g\n\004code\030\001 \001(" +
      "\tBY\212@VShort, unique string that identifi" +
      "es this location, scoped to the parent o" +
      "rganization.\022&\n\007partner\030\002 \001(\0132\020.partner." +
      "PartnerB\003\200@\001\022G\n\004name\030\003 \001(\tB9\212@6Name of t" +
      "his location, in human-readable verbose " +
      "form.\022u\n\005label\030\004 \001(\tBf\212@cLabel for this " +
      "location in the administrative dashboard" +
      ". If this is not specified, `name` is sh" +
      "own.\022h\n\005flags\030\005 \001(\0132\025.partner.PartnerFla" +
      "gsBB\212@?Flags that specify conditions app" +
      "lied to this partner location.\022P\n\007contac" +
      "t\030\007 \001(\0132\024.contact.ContactInfoB)\212@&Contac" +
      "t information for this location.\022\206\001\n\010bra" +
      "nding\030\006 \001(\0132\020.media.MediaItemBb\212@_Brandi" +
      "ng specific to this location. Partner-le" +
      "vel branding is used if this is left uns" +
      "pecified.\022R\n\007created\030\010 \001(\0132\021.temporal.In" +
      "stantB.\212@+Timestamp for when this record" +
      " was created.\022Y\n\010modified\030\t \001(\0132\021.tempor" +
      "al.InstantB4\212@1Timestamp for when this r" +
      "ecord was last modified.B \n\032io.bloombox." +
      "schema.partnerH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gen_bq_schema.BqField.getDescriptor(),
          io.bloombox.schema.partner.PartnerOuterClass.getDescriptor(),
          io.bloombox.schema.media.AttachedMedia.getDescriptor(),
          io.bloombox.schema.temporal.InstantOuterClass.getDescriptor(),
          io.bloombox.schema.contact.ContactInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_partner_PartnerLocationKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_partner_PartnerLocationKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_partner_PartnerLocationKey_descriptor,
        new java.lang.String[] { "Partner", "Code", });
    internal_static_partner_PartnerLocation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_partner_PartnerLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_partner_PartnerLocation_descriptor,
        new java.lang.String[] { "Code", "Partner", "Name", "Label", "Flags", "Contact", "Branding", "Created", "Modified", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(gen_bq_schema.BqField.description);
    registry.add(gen_bq_schema.BqField.ignore);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    gen_bq_schema.BqField.getDescriptor();
    io.bloombox.schema.partner.PartnerOuterClass.getDescriptor();
    io.bloombox.schema.media.AttachedMedia.getDescriptor();
    io.bloombox.schema.temporal.InstantOuterClass.getDescriptor();
    io.bloombox.schema.contact.ContactInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
