// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partners/v1beta1/PartnersService_Beta1.proto

package io.bloombox.schema.services.partners.v1beta1;

/**
 * <pre>
 * Specifies an operation to fetch an individual partner account.
 * </pre>
 *
 * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet}
 */
public  final class PartnerGet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bloombox.schema.services.partners.v1beta1.PartnerGet)
    PartnerGetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartnerGet.newBuilder() to construct.
  private PartnerGet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartnerGet() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartnerGet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bloombox.schema.services.partners.v1beta1.PartnerGet.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Builder.class);
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bloombox.schema.services.partners.v1beta1.PartnerGet.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID of the partner record to retrieve.
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    java.lang.String getPartnerId();
    /**
     * <pre>
     * ID of the partner record to retrieve.
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPartnerIdBytes();
  }
  /**
   * <pre>
   * Specifies a request to retrieve a partner.
   * </pre>
   *
   * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bloombox.schema.services.partners.v1beta1.PartnerGet.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      partnerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              partnerId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.Builder.class);
    }

    public static final int PARTNER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object partnerId_;
    /**
     * <pre>
     * ID of the partner record to retrieve.
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    public java.lang.String getPartnerId() {
      java.lang.Object ref = partnerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partnerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ID of the partner record to retrieve.
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerIdBytes() {
      java.lang.Object ref = partnerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partnerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPartnerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, partnerId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPartnerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, partnerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request)) {
        return super.equals(obj);
      }
      io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request other = (io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request) obj;

      boolean result = true;
      result = result && getPartnerId()
          .equals(other.getPartnerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARTNER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPartnerId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Specifies a request to retrieve a partner.
     * </pre>
     *
     * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bloombox.schema.services.partners.v1beta1.PartnerGet.Request)
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.Builder.class);
      }

      // Construct using io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        partnerId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Request_descriptor;
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request getDefaultInstanceForType() {
        return io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.getDefaultInstance();
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request build() {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request buildPartial() {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request result = new io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request(this);
        result.partnerId_ = partnerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request) {
          return mergeFrom((io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request other) {
        if (other == io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request.getDefaultInstance()) return this;
        if (!other.getPartnerId().isEmpty()) {
          partnerId_ = other.partnerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object partnerId_ = "";
      /**
       * <pre>
       * ID of the partner record to retrieve.
       * </pre>
       *
       * <code>string partner_id = 1;</code>
       */
      public java.lang.String getPartnerId() {
        java.lang.Object ref = partnerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partnerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ID of the partner record to retrieve.
       * </pre>
       *
       * <code>string partner_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPartnerIdBytes() {
        java.lang.Object ref = partnerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partnerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ID of the partner record to retrieve.
       * </pre>
       *
       * <code>string partner_id = 1;</code>
       */
      public Builder setPartnerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the partner record to retrieve.
       * </pre>
       *
       * <code>string partner_id = 1;</code>
       */
      public Builder clearPartnerId() {
        
        partnerId_ = getDefaultInstance().getPartnerId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the partner record to retrieve.
       * </pre>
       *
       * <code>string partner_id = 1;</code>
       */
      public Builder setPartnerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partnerId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bloombox.schema.services.partners.v1beta1.PartnerGet.Request)
    }

    // @@protoc_insertion_point(class_scope:bloombox.schema.services.partners.v1beta1.PartnerGet.Request)
    private static final io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request();
    }

    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bloombox.schema.services.partners.v1beta1.PartnerGet.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    boolean hasPartner();
    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    io.bloombox.schema.partner.PartnerAccount.Partner getPartner();
    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder getPartnerOrBuilder();
  }
  /**
   * <pre>
   * Specifies a response with a fetched partner.
   * </pre>
   *
   * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bloombox.schema.services.partners.v1beta1.PartnerGet.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.bloombox.schema.partner.PartnerAccount.Partner.Builder subBuilder = null;
              if (partner_ != null) {
                subBuilder = partner_.toBuilder();
              }
              partner_ = input.readMessage(io.bloombox.schema.partner.PartnerAccount.Partner.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(partner_);
                partner_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.Builder.class);
    }

    public static final int PARTNER_FIELD_NUMBER = 1;
    private io.bloombox.schema.partner.PartnerAccount.Partner partner_;
    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    public boolean hasPartner() {
      return partner_ != null;
    }
    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    public io.bloombox.schema.partner.PartnerAccount.Partner getPartner() {
      return partner_ == null ? io.bloombox.schema.partner.PartnerAccount.Partner.getDefaultInstance() : partner_;
    }
    /**
     * <pre>
     * Resulting partner record.
     * </pre>
     *
     * <code>.bloombox.schema.partner.Partner partner = 1;</code>
     */
    public io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder getPartnerOrBuilder() {
      return getPartner();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (partner_ != null) {
        output.writeMessage(1, getPartner());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (partner_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPartner());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response)) {
        return super.equals(obj);
      }
      io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response other = (io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response) obj;

      boolean result = true;
      result = result && (hasPartner() == other.hasPartner());
      if (hasPartner()) {
        result = result && getPartner()
            .equals(other.getPartner());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPartner()) {
        hash = (37 * hash) + PARTNER_FIELD_NUMBER;
        hash = (53 * hash) + getPartner().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Specifies a response with a fetched partner.
     * </pre>
     *
     * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bloombox.schema.services.partners.v1beta1.PartnerGet.Response)
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.Builder.class);
      }

      // Construct using io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (partnerBuilder_ == null) {
          partner_ = null;
        } else {
          partner_ = null;
          partnerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_Response_descriptor;
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response getDefaultInstanceForType() {
        return io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.getDefaultInstance();
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response build() {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response buildPartial() {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response result = new io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response(this);
        if (partnerBuilder_ == null) {
          result.partner_ = partner_;
        } else {
          result.partner_ = partnerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response) {
          return mergeFrom((io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response other) {
        if (other == io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response.getDefaultInstance()) return this;
        if (other.hasPartner()) {
          mergePartner(other.getPartner());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.bloombox.schema.partner.PartnerAccount.Partner partner_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.bloombox.schema.partner.PartnerAccount.Partner, io.bloombox.schema.partner.PartnerAccount.Partner.Builder, io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder> partnerBuilder_;
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public boolean hasPartner() {
        return partnerBuilder_ != null || partner_ != null;
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public io.bloombox.schema.partner.PartnerAccount.Partner getPartner() {
        if (partnerBuilder_ == null) {
          return partner_ == null ? io.bloombox.schema.partner.PartnerAccount.Partner.getDefaultInstance() : partner_;
        } else {
          return partnerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public Builder setPartner(io.bloombox.schema.partner.PartnerAccount.Partner value) {
        if (partnerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          partner_ = value;
          onChanged();
        } else {
          partnerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public Builder setPartner(
          io.bloombox.schema.partner.PartnerAccount.Partner.Builder builderForValue) {
        if (partnerBuilder_ == null) {
          partner_ = builderForValue.build();
          onChanged();
        } else {
          partnerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public Builder mergePartner(io.bloombox.schema.partner.PartnerAccount.Partner value) {
        if (partnerBuilder_ == null) {
          if (partner_ != null) {
            partner_ =
              io.bloombox.schema.partner.PartnerAccount.Partner.newBuilder(partner_).mergeFrom(value).buildPartial();
          } else {
            partner_ = value;
          }
          onChanged();
        } else {
          partnerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public Builder clearPartner() {
        if (partnerBuilder_ == null) {
          partner_ = null;
          onChanged();
        } else {
          partner_ = null;
          partnerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public io.bloombox.schema.partner.PartnerAccount.Partner.Builder getPartnerBuilder() {
        
        onChanged();
        return getPartnerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      public io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder getPartnerOrBuilder() {
        if (partnerBuilder_ != null) {
          return partnerBuilder_.getMessageOrBuilder();
        } else {
          return partner_ == null ?
              io.bloombox.schema.partner.PartnerAccount.Partner.getDefaultInstance() : partner_;
        }
      }
      /**
       * <pre>
       * Resulting partner record.
       * </pre>
       *
       * <code>.bloombox.schema.partner.Partner partner = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.bloombox.schema.partner.PartnerAccount.Partner, io.bloombox.schema.partner.PartnerAccount.Partner.Builder, io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder> 
          getPartnerFieldBuilder() {
        if (partnerBuilder_ == null) {
          partnerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.bloombox.schema.partner.PartnerAccount.Partner, io.bloombox.schema.partner.PartnerAccount.Partner.Builder, io.bloombox.schema.partner.PartnerAccount.PartnerOrBuilder>(
                  getPartner(),
                  getParentForChildren(),
                  isClean());
          partner_ = null;
        }
        return partnerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bloombox.schema.services.partners.v1beta1.PartnerGet.Response)
    }

    // @@protoc_insertion_point(class_scope:bloombox.schema.services.partners.v1beta1.PartnerGet.Response)
    private static final io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response();
    }

    public static io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public io.bloombox.schema.services.partners.v1beta1.PartnerGet.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet)) {
      return super.equals(obj);
    }
    io.bloombox.schema.services.partners.v1beta1.PartnerGet other = (io.bloombox.schema.services.partners.v1beta1.PartnerGet) obj;

    boolean result = true;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bloombox.schema.services.partners.v1beta1.PartnerGet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Specifies an operation to fetch an individual partner account.
   * </pre>
   *
   * Protobuf type {@code bloombox.schema.services.partners.v1beta1.PartnerGet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bloombox.schema.services.partners.v1beta1.PartnerGet)
      io.bloombox.schema.services.partners.v1beta1.PartnerGetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bloombox.schema.services.partners.v1beta1.PartnerGet.class, io.bloombox.schema.services.partners.v1beta1.PartnerGet.Builder.class);
    }

    // Construct using io.bloombox.schema.services.partners.v1beta1.PartnerGet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bloombox.schema.services.partners.v1beta1.PartnersServiceBeta1.internal_static_bloombox_schema_services_partners_v1beta1_PartnerGet_descriptor;
    }

    public io.bloombox.schema.services.partners.v1beta1.PartnerGet getDefaultInstanceForType() {
      return io.bloombox.schema.services.partners.v1beta1.PartnerGet.getDefaultInstance();
    }

    public io.bloombox.schema.services.partners.v1beta1.PartnerGet build() {
      io.bloombox.schema.services.partners.v1beta1.PartnerGet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.bloombox.schema.services.partners.v1beta1.PartnerGet buildPartial() {
      io.bloombox.schema.services.partners.v1beta1.PartnerGet result = new io.bloombox.schema.services.partners.v1beta1.PartnerGet(this);
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bloombox.schema.services.partners.v1beta1.PartnerGet) {
        return mergeFrom((io.bloombox.schema.services.partners.v1beta1.PartnerGet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bloombox.schema.services.partners.v1beta1.PartnerGet other) {
      if (other == io.bloombox.schema.services.partners.v1beta1.PartnerGet.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bloombox.schema.services.partners.v1beta1.PartnerGet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bloombox.schema.services.partners.v1beta1.PartnerGet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bloombox.schema.services.partners.v1beta1.PartnerGet)
  }

  // @@protoc_insertion_point(class_scope:bloombox.schema.services.partners.v1beta1.PartnerGet)
  private static final io.bloombox.schema.services.partners.v1beta1.PartnerGet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bloombox.schema.services.partners.v1beta1.PartnerGet();
  }

  public static io.bloombox.schema.services.partners.v1beta1.PartnerGet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartnerGet>
      PARSER = new com.google.protobuf.AbstractParser<PartnerGet>() {
    public PartnerGet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartnerGet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartnerGet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartnerGet> getParserForType() {
    return PARSER;
  }

  public io.bloombox.schema.services.partners.v1beta1.PartnerGet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

