// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content/Brand.proto

package io.opencannabis.schema.content;

public interface BrandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opencannabis.content.Brand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.opencannabis.content.Name name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>.opencannabis.content.Name name = 1;</code>
   */
  io.opencannabis.schema.content.Name getName();
  /**
   * <code>.opencannabis.content.Name name = 1;</code>
   */
  io.opencannabis.schema.content.NameOrBuilder getNameOrBuilder();

  /**
   * <code>.opencannabis.content.Brand parent = 2;</code>
   */
  boolean hasParent();
  /**
   * <code>.opencannabis.content.Brand parent = 2;</code>
   */
  io.opencannabis.schema.content.Brand getParent();
  /**
   * <code>.opencannabis.content.Brand parent = 2;</code>
   */
  io.opencannabis.schema.content.BrandOrBuilder getParentOrBuilder();

  /**
   * <code>.opencannabis.content.Content summary = 3;</code>
   */
  boolean hasSummary();
  /**
   * <code>.opencannabis.content.Content summary = 3;</code>
   */
  io.opencannabis.schema.content.Content getSummary();
  /**
   * <code>.opencannabis.content.Content summary = 3;</code>
   */
  io.opencannabis.schema.content.ContentOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   *Media
   * </pre>
   *
   * <code>repeated .opencannabis.media.MediaItem media = 20;</code>
   */
  java.util.List<io.opencannabis.schema.media.MediaItem> 
      getMediaList();
  /**
   * <pre>
   *Media
   * </pre>
   *
   * <code>repeated .opencannabis.media.MediaItem media = 20;</code>
   */
  io.opencannabis.schema.media.MediaItem getMedia(int index);
  /**
   * <pre>
   *Media
   * </pre>
   *
   * <code>repeated .opencannabis.media.MediaItem media = 20;</code>
   */
  int getMediaCount();
  /**
   * <pre>
   *Media
   * </pre>
   *
   * <code>repeated .opencannabis.media.MediaItem media = 20;</code>
   */
  java.util.List<? extends io.opencannabis.schema.media.MediaItemOrBuilder> 
      getMediaOrBuilderList();
  /**
   * <pre>
   *Media
   * </pre>
   *
   * <code>repeated .opencannabis.media.MediaItem media = 20;</code>
   */
  io.opencannabis.schema.media.MediaItemOrBuilder getMediaOrBuilder(
      int index);
}
