// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry/v1beta3/GenericEvents_Beta3.proto

package io.bloombox.schema.services.telemetry.v1beta3;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.telemetry.v1beta3.Event)
    com.google.protobuf.MessageOrBuilder {
}
