// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/ProductKind.proto

package io.opencannabis.schema.base;

public final class BaseProductKind {
  private BaseProductKind() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026base/ProductKind.proto\022\021opencannabis.b" +
      "ase*\200\001\n\013ProductKind\022\013\n\007FLOWERS\020\000\022\013\n\007EDIB" +
      "LES\020\001\022\014\n\010EXTRACTS\020\002\022\014\n\010PREROLLS\020\003\022\016\n\nAPO" +
      "THECARY\020\004\022\016\n\nCARTRIDGES\020\005\022\n\n\006PLANTS\020\006\022\017\n" +
      "\013MERCHANDISE\020\007B8\n\033io.opencannabis.schema" +
      ".baseB\017BaseProductKindH\001P\001\242\002\003OCSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
