// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry/v1beta4/GenericEvents_Beta4.proto

package io.bloombox.schema.services.telemetry.v1beta4;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bloombox.schema.services.telemetry.v1beta4.Event)
    com.google.protobuf.MessageOrBuilder {
}
