// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media/v1beta1/MediaService_Beta1.proto

package io.bloombox.schema.services.media.v1beta1;

public interface OperationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bloombox.schema.services.media.v1beta1.OperationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resulting key, provisioned fresh for this media item.
   * </pre>
   *
   * <code>.opencannabis.media.MediaKey key = 1;</code>
   */
  boolean hasKey();
  /**
   * <pre>
   * Resulting key, provisioned fresh for this media item.
   * </pre>
   *
   * <code>.opencannabis.media.MediaKey key = 1;</code>
   */
  io.opencannabis.schema.media.MediaItemKey.MediaKey getKey();
  /**
   * <pre>
   * Resulting key, provisioned fresh for this media item.
   * </pre>
   *
   * <code>.opencannabis.media.MediaKey key = 1;</code>
   */
  io.opencannabis.schema.media.MediaItemKey.MediaKeyOrBuilder getKeyOrBuilder();
}
